language: scala
jdk:
- oraclejdk8
scala:
- 2.12.1
script:
- scripts/do_build.sh
deploy:
  provider: bintray
  file: descriptor.json
  user: popiel
  key:
    secure: gRzE1bpckKbBo5COYaRWLkWkze3Km/Cic5lVmwE2l9AO8XRJEVu644wxELNXy8I4GJxuajJ/TMskvyUDY/25UJPcG88fX/FDWx/7Iw7vzdGIxIxppHsEaZSeRcUuRIlxpMEUSYPjCViUBdxflhjM06yDrqW6e2+ofFwuxYQNhZ9vzc2Whkgia+maqbcTC8GLgBwlDUXR0px0lgTBNNS21UnfXvOMqrc4Y3gd9rz7/FtqS4FGrLvwZ1vKYfbrX35SsOE7RmcYCKaLWTI0ATYWWru2cbhPDpf5LvT1w2zq2XNqUDYL4NG5Q4nM/H//VDW2+82Xqq5xYJuxa09wgIdXL8XypjODyZFeAElbHwkXdhiVkpxWskMhrl38qbUi8nBfN1FK9xYArjrjWI1xvZmAMOofYsxu7fyRhJNk5JRYoeX3ctwAgP84SnM/jRsJI/tPezA8+jIDDtbQSncIEv2J3AwslmOVAMJaC7xZgo/FAuPwiP55Tk8IRdt4uQkgMxANflbHbIop+HkKkVkPkASBEjk0AyOwLYqw2mGUo95IFipHteSAPE8NjlNSNYQaVwnYEUG5+tE4rt6eHKrOC0zxA6s1UVHH9rd1hnUI52xixrZtw375o+k32jCHBN8cIb9zTGdZzTp6Yf1ryMDCVE2I9ANT1GCdAc0qidFQK963dA4=
env:
  global:
    secure: qZSLTr30NZRLJIPramRVvp3BUn+wgvppMsPc/np1+tUUZjm2xT3XMIclDHHUa5zHCu6nmPmFmDzbDOJwg2TbknwIesi9T8MoQs80s3b3NFOhD6Y0ul4gg1YKYRzdXwDfJEm6dHQyfoGEs2Hok6dLcoSCr8rG6K1bFeJ3V2JbSYtyyoJhtMJsojNYRFMFOkuu+hz2OgQ67oMsyYmLUwvwlwJxIQkUXTeqcQSWTKUZs1OYxLkEnjAnUh4KEzKXItTjMfxz1X/FOefdwluG1wuBJDrBhYNcGn4lVHrYxc34geGoxPLK0UGd/HK28T6PsIvMVeKIUZCHoDCy3CMkG1VKzbIjgvrLmmxfs6gzUpnj/h/A073t0/9d/0EPvSs61dFhDvmo6CLPLwRgUILBD2KgIT6/bJ8J4e3qFxQQOjaFGFmJbX4pQBlfmLcdi4J9Ymd4F9VY4MbLHDtWC3BkNpaUHc4SmSKv+JETdnh5Ow8OegM56VAh1lRHdH2ome+1VRj7lmGHKEs2MgBQsjs/Iiyt8AwG0e2VhVZGE4RCDjsDX5Ls6lq/gSS2o6/y/wNUkFrzEq8/iypT1Fg+HZLQ9K6Yb8RwlVhNtz2D9pOYHAxx7Nooo1VUvBrdWxU83jcbBLYNCMOEkYi8P0W3gWYqzWnY5cIS8/dT5Iui1VjC7wmD6yo=
