// DON'T EDIT THIS FILE.
// This file is auto generated by sbt-lock 0.3.0.
// https://github.com/tkawachi/sbt-lock/
dependencyOverrides in ThisBuild ++= Set(
  "ch.qos.logback" % "logback-classic" % "1.1.7",
  "ch.qos.logback" % "logback-core" % "1.1.7",
  "com.typesafe" % "config" % "1.3.0",
  "com.typesafe" % "ssl-config-core_2.12" % "0.2.1",
  "com.typesafe.akka" % "akka-actor_2.12" % "2.4.14",
  "com.typesafe.akka" % "akka-protobuf_2.12" % "2.4.14",
  "com.typesafe.akka" % "akka-remote_2.12" % "2.4.14",
  "com.typesafe.akka" % "akka-slf4j_2.12" % "2.4.14",
  "com.typesafe.akka" % "akka-stream_2.12" % "2.4.14",
  "com.typesafe.akka" % "akka-testkit_2.12" % "2.4.14",
  "io.aeron" % "aeron-client" % "1.0.4",
  "io.aeron" % "aeron-driver" % "1.0.4",
  "io.netty" % "netty" % "3.10.6.Final",
  "io.spray" % "spray-json_2.12" % "1.3.2",
  "org.agrona" % "Agrona" % "0.9.0",
  "org.aspectj" % "aspectjrt" % "1.8.9",
  "org.aspectj" % "aspectjtools" % "1.8.9",
  "org.aspectj" % "aspectjweaver" % "1.8.9",
  "org.reactivestreams" % "reactive-streams" % "1.0.0",
  "org.scala-lang.modules" % "scala-java8-compat_2.12" % "0.8.0",
  "org.scala-lang.modules" % "scala-parser-combinators_2.12" % "1.0.4",
  "org.scalactic" % "scalactic_2.12" % "3.0.0",
  "org.slf4j" % "slf4j-api" % "1.7.21",
  "org.uncommons.maths" % "uncommons-maths" % "1.2.2a"
)
// LIBRARY_DEPENDENCIES_HASH 9421f10bfdc0b913ac90fe303cccbfae039eddc4
